type MCQSeed = {
  questionText: string;
  options: [string, string, string, string];
  correctAnswer: number;
  category: 'cyber' | 'logic' | 'coding';
  difficulty: 'easy' | 'medium';
  points: number;
  order: number;
};

type TestCase = { input: string; expectedOutput: string };

type CodingSeed = {
  title: string;
  description: string;
  inputFormat: string;
  outputFormat: string;
  constraints: string;
  sampleInput: string;
  sampleOutput: string;
  hiddenTestCases: TestCase[];
  difficulty: 'easy' | 'medium';
  points: number;
  timeLimit: number;
  memoryLimit: number;
  order: number;
  starterCode: Record<'c' | 'cpp' | 'java' | 'python', string>;
  wrappers?: Partial<Record<'c' | 'cpp' | 'java' | 'python', string>>;
};

export const ROUND1_MCQ_BANK: MCQSeed[] = [
  {
    questionText: 'Agent Mira must scan 5 encrypted IDs in a loop. If the loop starts at index 0 and ends at index 4 inclusive, how many times does it run?',
    options: ['4', '5', '6', 'Depends on the compiler'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 1,
  },
  {
    questionText: 'A surveillance list stores targets as an array. Which operation gives direct access to the item at index i in O(1) time?',
    options: ['Linear search', 'Direct indexing', 'Binary tree traversal', 'Stack pop'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 2,
  },
  {
    questionText: 'A decoder checks whether a secret code is even using n % 2 == 0. What is the result for the code 28?',
    options: ['false', 'true', 'undefined', 'runtime error'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 3,
  },
  {
    questionText: 'Agent K receives the string "spy". After concatenating "net", what is the result?',
    options: ['spynet', 'spy net', 'netspy', 'spy+net'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 4,
  },
  {
    questionText: 'Mission Control uses a stack to track last-entered safehouses. Which operation removes the most recent safehouse?',
    options: ['enqueue', 'dequeue', 'pop', 'peek'],
    correctAnswer: 2,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 5,
  },
  {
    questionText: 'In a binary tree of informants, the topmost node is called the:',
    options: ['leaf', 'root', 'branch', 'edge'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 6,
  },
  {
    questionText: 'An espionage script contains: x = 7; y = x++; What value is stored in y in languages where post-increment returns the old value?',
    options: ['6', '7', '8', '14'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 7,
  },
  {
    questionText: 'If a function scans every dossier in a list of n dossiers exactly once, its time complexity is:',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    correctAnswer: 2,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 8,
  },
  {
    questionText: 'Agent Noor runs two nested loops over n encrypted chips. Which complexity is most likely?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
    correctAnswer: 3,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 9,
  },
  {
    questionText: 'A branch in the infiltration plan executes only when clearance >= 7. If clearance is 9, what happens?',
    options: ['The if-block runs', 'The else-block runs', 'Nothing can be determined', 'The program crashes'],
    correctAnswer: 0,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 10,
  },
  {
    questionText: 'Which data structure is best suited for a "last clue in, first clue out" behavior?',
    options: ['Queue', 'Stack', 'Linked list only', 'Binary search tree'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 11,
  },
  {
    questionText: 'What is the output of this pseudocode? code = 3; print(code * code + 1)',
    options: ['7', '9', '10', '12'],
    correctAnswer: 2,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 12,
  },
  {
    questionText: 'In a binary search tree storing access levels, where is a smaller key placed relative to a node?',
    options: ['To the left', 'To the right', 'Only at the root', 'Randomly'],
    correctAnswer: 0,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 13,
  },
  {
    questionText: 'A mission planner uses recursion on a balanced binary tree of n nodes to find a key. Average search time is closest to:',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 14,
  },
  {
    questionText: 'If the code is: int signal = 0; while(signal < 3) signal++; What is the final value of signal?',
    options: ['0', '2', '3', '4'],
    correctAnswer: 2,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 15,
  },
  {
    questionText: 'A string comparison should be case-sensitive for passcodes. Which pair should be treated as different?',
    options: ['agent and agent', 'Spy and spy', '007 and 007', 'red and red'],
    correctAnswer: 1,
    category: 'cyber',
    difficulty: 'easy',
    points: 1,
    order: 16,
  },
  {
    questionText: 'An in-order traversal of a binary search tree of secret IDs returns them in:',
    options: ['Reverse insertion order', 'Sorted order', 'Level order always', 'Random order'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'medium',
    points: 1,
    order: 17,
  },
  {
    questionText: 'If a stack currently contains [alpha, bravo, charlie] with charlie on top, what is removed first?',
    options: ['alpha', 'bravo', 'charlie', 'all at once'],
    correctAnswer: 2,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 18,
  },
  {
    questionText: 'Which logic condition allows entry only if the agent has a badge AND knows the code word?',
    options: ['badge || codeword', '!badge', 'badge && codeword', 'badge == codeword'],
    correctAnswer: 2,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 19,
  },
  {
    questionText: 'Output question: count = 1; for i in range(3): count += i. What is count at the end?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 20,
  },
  {
    questionText: 'An array of 8 microfilms is searched using binary search. The worst-case time complexity is:',
    options: ['O(log n)', 'O(n)', 'O(n^2)', 'O(2^n)'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 21,
  },
  {
    questionText: 'A full binary tree level contains 8 field agents. Which level number could it be if the root is level 0?',
    options: ['1', '2', '3', '4'],
    correctAnswer: 3,
    category: 'logic',
    difficulty: 'medium',
    points: 1,
    order: 22,
  },
  {
    questionText: 'If a decryption function calls itself with n - 1 until n becomes 0, how many recursive calls occur for n = 4 before the base case returns?',
    options: ['3', '4', '5', '8'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 23,
  },
  {
    questionText: 'Which of the following is the best description of encapsulation in an espionage software system?',
    options: ['Hiding data and exposing safe methods', 'Sorting data quickly', 'Using only global variables', 'Avoiding functions'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 24,
  },
  {
    questionText: 'A queue of outgoing messages behaves as:',
    options: ['LIFO', 'FIFO', 'Sorted by size', 'Random removal'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 25,
  },
  {
    questionText: 'Output question: if (4 > 2 && 1 < 0) print("safe") else print("abort"). What is printed?',
    options: ['safe', 'abort', '4', 'No output'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 26,
  },
  {
    questionText: 'A spy network graph is stored as an adjacency list. Traversing all nodes and edges once takes:',
    options: ['O(V + E)', 'O(VE)', 'O(log V)', 'O(1)'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 27,
  },
  {
    questionText: 'When comparing two approaches to verify a password of length m against one guess, the cost is most closely:',
    options: ['O(1)', 'O(log m)', 'O(m)', 'O(m^2)'],
    correctAnswer: 2,
    category: 'cyber',
    difficulty: 'medium',
    points: 1,
    order: 28,
  },
  {
    questionText: 'If the preorder traversal of a tree starts with node X, what must X be?',
    options: ['A leaf', 'The root of the current subtree', 'The largest value', 'The smallest value'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'medium',
    points: 1,
    order: 29,
  },
  {
    questionText: 'Which approach is safest for storing agent credentials in software?',
    options: ['Plain text file', 'Hashed representation', 'Printed in logs', 'Hardcoded in frontend code'],
    correctAnswer: 1,
    category: 'cyber',
    difficulty: 'easy',
    points: 1,
    order: 30,
  },
  {
    questionText: 'Agent J discovers a suspicious email asking for their mainframe password. This social engineering tactic is known as:',
    options: ['Spoofing', 'Phishing', 'Sniffing', 'DDoS'],
    correctAnswer: 1,
    category: 'cyber',
    difficulty: 'easy',
    points: 1,
    order: 31,
  },
  {
    questionText: 'A Caesar cipher shifts "ABC" by 3 positions. What is the encrypted version?',
    options: ['DEF', 'XYZ', 'GHI', 'CBA'],
    correctAnswer: 0,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 32,
  },
  {
    questionText: 'If an operative tries to write 12 bytes of data into a 10-byte buffer, what occurs?',
    options: ['Memory leak', 'Buffer overflow', 'Stack underflow', 'Indexing error'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 33,
  },
  {
    questionText: 'In a network of 4 agents where every agent connects to exactly 2 others, the network forms a:',
    options: ['Star', 'Tree', 'Cycle', 'Bipartite graph'],
    correctAnswer: 2,
    category: 'logic',
    difficulty: 'medium',
    points: 1,
    order: 34,
  },
  {
    questionText: 'Searching a sorted list of 1,000,000 dossiers using Binary Search takes at most how many comparisons?',
    options: ['20', '100', '1000', '500'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 35,
  },
  {
    questionText: 'Which protocol is most secure for transmitting classified surveillance data over the web?',
    options: ['HTTP', 'HTTPS', 'FTP', 'Telnet'],
    correctAnswer: 1,
    category: 'cyber',
    difficulty: 'easy',
    points: 1,
    order: 36,
  },
  {
    questionText: 'A secret sequence follows this pattern: 1, 1, 2, 3, 5, 8, ... What is the next number?',
    options: ['10', '12', '13', '15'],
    correctAnswer: 2,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 37,
  },
  {
    questionText: 'In C++, what does the "*" operator do when placed before a pointer variable like *ptr?',
    options: ['Multiplication', 'Dereferencing', 'Address-of', 'Deletion'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 38,
  },
  {
    questionText: 'Operative A is in Paris, B is in London. Some agents are in both lists. The set of agents in either list is the:',
    options: ['Intersection', 'Union', 'Complement', 'Difference'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 39,
  },
  {
    questionText: 'An attacker leaves a virus-infected USB drive in a parking lot, hoping a staff member picks it up. This is:',
    options: ['Baiting', 'Tailgating', 'Quid pro quo', 'Vishing'],
    correctAnswer: 0,
    category: 'cyber',
    difficulty: 'medium',
    points: 1,
    order: 40,
  },
  {
    questionText: 'To store names of safehouses where each points to the next, which data structure is most efficient?',
    options: ['Array', 'Linked List', 'Hash Map', 'Stack'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 41,
  },
  {
    questionText: 'If a logic gate only outputs TRUE when both inputs are DIFFERENT, it is a:',
    options: ['AND gate', 'OR gate', 'XOR gate', 'NAND gate'],
    correctAnswer: 2,
    category: 'logic',
    difficulty: 'medium',
    points: 1,
    order: 42,
  },
  {
    questionText: 'What is the binary representation of the decimal number 13?',
    options: ['1011', '1101', '1110', '1001'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'easy',
    points: 1,
    order: 43,
  },
  {
    questionText: 'A system that monitors and controls incoming and outgoing network traffic based on security rules is a:',
    options: ['Proxy', 'Antivirus', 'Firewall', 'Switch'],
    correctAnswer: 2,
    category: 'cyber',
    difficulty: 'easy',
    points: 1,
    order: 44,
  },
  {
    questionText: 'If the probability of mission success is 0.7, what is the probability of failure?',
    options: ['0.3', '0.5', '0.7', '1.0'],
    correctAnswer: 0,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 45,
  },
  {
    questionText: 'Recursive functions run the risk of causing a "Stack Overflow" primarily because of:',
    options: ['Excessive memory allocation', 'Infinite recursion depth', 'Large input arrays', 'Poor time complexity'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 46,
  },
  {
    questionText: 'A vault opens if (A OR B) is true. If A is false and B is true, does the vault open?',
    options: ['Yes', 'No', 'Only if A becomes true', 'The system errors'],
    correctAnswer: 0,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 47,
  },
  {
    questionText: 'Which encryption standard uses 128, 192, or 256-bit keys and is the current industry standard?',
    options: ['DES', 'AES', 'Blowfish', 'MD5'],
    correctAnswer: 1,
    category: 'cyber',
    difficulty: 'medium',
    points: 1,
    order: 48,
  },
  {
    questionText: 'Sorting n dossier names using Merge Sort has a worst-case time complexity of:',
    options: ['O(n)', 'O(n^2)', 'O(n log n)', 'O(log n)'],
    correctAnswer: 2,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 49,
  },
  {
    questionText: 'A biometric lock uses AND logic for fingerprint and retinal scan. If the fingerprint matches but retina does not, the output is:',
    options: ['TRUE', 'FALSE', 'DEPENDS', 'ERROR'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'easy',
    points: 1,
    order: 50,
  },
];

const ID_INPUT = 'The first line contains an integer n. The second line contains n integers representing dossier values.';
const DEFAULT_CONSTRAINTS = '1 <= n <= 2 * 10^5\nValues fit in 32-bit signed integers.';

const STANDARD_STARTER: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdio.h>\n\nint main(void) {\n    // Write your solution here.\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    // Write your solution here.\n    return 0;\n}\n',
  java: 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        // Write your solution here.\n    }\n}\n',
  python: '# Write your solution here.\n',
};

const REGISTRY_STARTER: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdlib.h>\n#include <string.h>\n\ntypedef struct Registry Registry;\n\nRegistry* create_registry(void) {\n    return NULL;\n}\n\nvoid add_agent(Registry* registry, const char* code, int score) {\n}\n\nvoid update_agent(Registry* registry, const char* code, int delta) {\n}\n\nint get_score(Registry* registry, const char* code) {\n    return -1;\n}\n\nint top_score(Registry* registry) {\n    return -1;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nclass Registry {\npublic:\n    void addAgent(const string& code, int score) {\n    }\n\n    void updateAgent(const string& code, int delta) {\n    }\n\n    int getScore(const string& code) {\n        return -1;\n    }\n\n    int topScore() {\n        return -1;\n    }\n};\n',
  java: 'import java.util.*;\n\nclass Registry {\n    public void addAgent(String code, int score) {\n    }\n\n    public void updateAgent(String code, int delta) {\n    }\n\n    public int getScore(String code) {\n        return -1;\n    }\n\n    public int topScore() {\n        return -1;\n    }\n}\n',
  python: 'class Registry:\n    def __init__(self):\n        pass\n\n    def add_agent(self, code: str, score: int) -> None:\n        pass\n\n    def update_agent(self, code: str, delta: int) -> None:\n        pass\n\n    def get_score(self, code: str) -> int:\n        return -1\n\n    def top_score(self) -> int:\n        return -1\n',
};

const INVENTORY_STARTER: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdlib.h>\n#include <string.h>\n\ntypedef struct Inventory Inventory;\n\nInventory* create_inventory(void) {\n    return NULL;\n}\n\nvoid stock_item(Inventory* inventory, const char* itemType, int count) {\n}\n\nvoid use_item(Inventory* inventory, const char* itemType, int count) {\n}\n\nint count_item(Inventory* inventory, const char* itemType) {\n    return 0;\n}\n\nint total_items(Inventory* inventory) {\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nclass Inventory {\npublic:\n    void stockItem(const string& itemType, int count) {\n    }\n\n    void useItem(const string& itemType, int count) {\n    }\n\n    int countItem(const string& itemType) {\n        return 0;\n    }\n\n    int totalItems() {\n        return 0;\n    }\n};\n',
  java: 'import java.util.*;\n\nclass Inventory {\n    public void stockItem(String itemType, int count) {\n    }\n\n    public void useItem(String itemType, int count) {\n    }\n\n    public int countItem(String itemType) {\n        return 0;\n    }\n\n    public int totalItems() {\n        return 0;\n    }\n}\n',
  python: 'class Inventory:\n    def __init__(self):\n        pass\n\n    def stock_item(self, item_type: str, count: int) -> None:\n        pass\n\n    def use_item(self, item_type: str, count: int) -> None:\n        pass\n\n    def count_item(self, item_type: str) -> int:\n        return 0\n\n    def total_items(self) -> int:\n        return 0\n',
};

const ANALYZER_STARTER: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdlib.h>\n#include <string.h>\n\ntypedef struct ReportAnalyzer ReportAnalyzer;\n\nReportAnalyzer* create_analyzer(void) {\n    return NULL;\n}\n\nvoid add_report(ReportAnalyzer* analyzer, const char* word) {\n}\n\nint has_report(ReportAnalyzer* analyzer, const char* word) {\n    return 0;\n}\n\nint longest_report(ReportAnalyzer* analyzer) {\n    return 0;\n}\n\nint report_count(ReportAnalyzer* analyzer) {\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nclass ReportAnalyzer {\npublic:\n    void addReport(const string& word) {\n    }\n\n    bool hasReport(const string& word) {\n        return false;\n    }\n\n    int longestReport() {\n        return 0;\n    }\n\n    int reportCount() {\n        return 0;\n    }\n};\n',
  java: 'import java.util.*;\n\nclass ReportAnalyzer {\n    public void addReport(String word) {\n    }\n\n    public boolean hasReport(String word) {\n        return false;\n    }\n\n    public int longestReport() {\n        return 0;\n    }\n\n    public int reportCount() {\n        return 0;\n    }\n}\n',
  python: 'class ReportAnalyzer:\n    def __init__(self):\n        pass\n\n    def add_report(self, word: str) -> None:\n        pass\n\n    def has_report(self, word: str) -> bool:\n        return False\n\n    def longest_report(self) -> int:\n        return 0\n\n    def report_count(self) -> int:\n        return 0\n',
};

const REGISTRY_WRAPPERS: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n__USER_CODE__\n\ntypedef struct Entry {\n    char code[64];\n    int score;\n} Entry;\n\nstruct Registry {\n    Entry items[200005];\n    int size;\n};\n\nint main(void) {\n    int q;\n    if (scanf(\"%d\", &q) != 1) return 0;\n    Registry* registry = create_registry();\n    char cmd[16], code[64];\n    int value;\n    while (q--) {\n        scanf(\"%15s\", cmd);\n        if (strcmp(cmd, \"ADD\") == 0) {\n            scanf(\"%63s %d\", code, &value);\n            add_agent(registry, code, value);\n        } else if (strcmp(cmd, \"UPDATE\") == 0) {\n            scanf(\"%63s %d\", code, &value);\n            update_agent(registry, code, value);\n        } else if (strcmp(cmd, \"GET\") == 0) {\n            scanf(\"%63s\", code);\n            printf(\"%d\\n\", get_score(registry, code));\n        } else {\n            int best = top_score(registry);\n            if (best == -1) printf(\"EMPTY\\n\");\n            else printf(\"%d\\n\", best);\n        }\n    }\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\n__USER_CODE__\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n    int q;\n    if (!(cin >> q)) return 0;\n    Registry registry;\n    while (q--) {\n        string cmd;\n        cin >> cmd;\n        if (cmd == \"ADD\") {\n            string code;\n            int score;\n            cin >> code >> score;\n            registry.addAgent(code, score);\n        } else if (cmd == \"UPDATE\") {\n            string code;\n            int delta;\n            cin >> code >> delta;\n            registry.updateAgent(code, delta);\n        } else if (cmd == \"GET\") {\n            string code;\n            cin >> code;\n            cout << registry.getScore(code) << \"\\n\";\n        } else {\n            int best = registry.topScore();\n            if (best == -1) cout << \"EMPTY\\n\";\n            else cout << best << \"\\n\";\n        }\n    }\n    return 0;\n}\n',
  java: 'import java.util.*;\n\n__USER_CODE__\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int q = sc.nextInt();\n        Registry registry = new Registry();\n        StringBuilder out = new StringBuilder();\n        while (q-- > 0) {\n            String cmd = sc.next();\n            if (\"ADD\".equals(cmd)) {\n                registry.addAgent(sc.next(), sc.nextInt());\n            } else if (\"UPDATE\".equals(cmd)) {\n                registry.updateAgent(sc.next(), sc.nextInt());\n            } else if (\"GET\".equals(cmd)) {\n                out.append(registry.getScore(sc.next())).append(\'\\n\');\n            } else {\n                int best = registry.topScore();\n                out.append(best == -1 ? \"EMPTY\" : Integer.toString(best)).append(\'\\n\');\n            }\n        }\n        System.out.print(out);\n    }\n}\n',
  python: '__USER_CODE__\n\nimport sys\n\n\ndef main() -> None:\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    q = int(data[0])\n    idx = 1\n    registry = Registry()\n    out = []\n    for _ in range(q):\n        cmd = data[idx]\n        idx += 1\n        if cmd == \"ADD\":\n            registry.add_agent(data[idx], int(data[idx + 1]))\n            idx += 2\n        elif cmd == \"UPDATE\":\n            registry.update_agent(data[idx], int(data[idx + 1]))\n            idx += 2\n        elif cmd == \"GET\":\n            out.append(str(registry.get_score(data[idx])))\n            idx += 1\n        else:\n            best = registry.top_score()\n            out.append(\"EMPTY\" if best == -1 else str(best))\n    sys.stdout.write(\"\\n\".join(out))\n    if out:\n        sys.stdout.write(\"\\n\")\n\n\nif __name__ == \"__main__\":\n    main()\n',
};

const INVENTORY_WRAPPERS: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n__USER_CODE__\n\ntypedef struct ItemEntry {\n    char name[64];\n    int count;\n} ItemEntry;\n\nstruct Inventory {\n    ItemEntry items[200005];\n    int size;\n};\n\nint main(void) {\n    int q;\n    if (scanf(\"%d\", &q) != 1) return 0;\n    Inventory* inventory = create_inventory();\n    char cmd[16], item[64];\n    int count;\n    while (q--) {\n        scanf(\"%15s\", cmd);\n        if (strcmp(cmd, \"STOCK\") == 0) {\n            scanf(\"%63s %d\", item, &count);\n            stock_item(inventory, item, count);\n        } else if (strcmp(cmd, \"USE\") == 0) {\n            scanf(\"%63s %d\", item, &count);\n            use_item(inventory, item, count);\n        } else if (strcmp(cmd, \"COUNT\") == 0) {\n            scanf(\"%63s\", item);\n            printf(\"%d\\n\", count_item(inventory, item));\n        } else {\n            printf(\"%d\\n\", total_items(inventory));\n        }\n    }\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\n__USER_CODE__\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n    int q;\n    if (!(cin >> q)) return 0;\n    Inventory inventory;\n    while (q--) {\n        string cmd;\n        cin >> cmd;\n        if (cmd == \"STOCK\") {\n            string item;\n            int count;\n            cin >> item >> count;\n            inventory.stockItem(item, count);\n        } else if (cmd == \"USE\") {\n            string item;\n            int count;\n            cin >> item >> count;\n            inventory.useItem(item, count);\n        } else if (cmd == \"COUNT\") {\n            string item;\n            cin >> item;\n            cout << inventory.countItem(item) << \"\\n\";\n        } else {\n            cout << inventory.totalItems() << \"\\n\";\n        }\n    }\n    return 0;\n}\n',
  java: 'import java.util.*;\n\n__USER_CODE__\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int q = sc.nextInt();\n        Inventory inventory = new Inventory();\n        StringBuilder out = new StringBuilder();\n        while (q-- > 0) {\n            String cmd = sc.next();\n            if (\"STOCK\".equals(cmd)) {\n                inventory.stockItem(sc.next(), sc.nextInt());\n            } else if (\"USE\".equals(cmd)) {\n                inventory.useItem(sc.next(), sc.nextInt());\n            } else if (\"COUNT\".equals(cmd)) {\n                out.append(inventory.countItem(sc.next())).append(\'\\n\');\n            } else {\n                out.append(inventory.totalItems()).append(\'\\n\');\n            }\n        }\n        System.out.print(out);\n    }\n}\n',
  python: '__USER_CODE__\n\nimport sys\n\n\ndef main() -> None:\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    q = int(data[0])\n    idx = 1\n    inventory = Inventory()\n    out = []\n    for _ in range(q):\n        cmd = data[idx]\n        idx += 1\n        if cmd == \"STOCK\":\n            inventory.stock_item(data[idx], int(data[idx + 1]))\n            idx += 2\n        elif cmd == \"USE\":\n            inventory.use_item(data[idx], int(data[idx + 1]))\n            idx += 2\n        elif cmd == \"COUNT\":\n            out.append(str(inventory.count_item(data[idx])))\n            idx += 1\n        else:\n            out.append(str(inventory.total_items()))\n    sys.stdout.write(\"\\n\".join(out))\n    if out:\n        sys.stdout.write(\"\\n\")\n\n\nif __name__ == \"__main__\":\n    main()\n',
};

const ANALYZER_WRAPPERS: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n__USER_CODE__\n\ntypedef struct ReportEntry {\n    char word[128];\n} ReportEntry;\n\nstruct ReportAnalyzer {\n    ReportEntry items[200005];\n    int size;\n    int longest;\n};\n\nint main(void) {\n    int q;\n    if (scanf(\"%d\", &q) != 1) return 0;\n    ReportAnalyzer* analyzer = create_analyzer();\n    char cmd[16], word[128];\n    while (q--) {\n        scanf(\"%15s\", cmd);\n        if (strcmp(cmd, \"ADD\") == 0) {\n            scanf(\"%127s\", word);\n            add_report(analyzer, word);\n        } else if (strcmp(cmd, \"HAS\") == 0) {\n            scanf(\"%127s\", word);\n            printf(has_report(analyzer, word) ? \"YES\\n\" : \"NO\\n\");\n        } else if (strcmp(cmd, \"LONGEST\") == 0) {\n            printf(\"%d\\n\", longest_report(analyzer));\n        } else {\n            printf(\"%d\\n\", report_count(analyzer));\n        }\n    }\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\n__USER_CODE__\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n    int q;\n    if (!(cin >> q)) return 0;\n    ReportAnalyzer analyzer;\n    while (q--) {\n        string cmd;\n        cin >> cmd;\n        if (cmd == \"ADD\") {\n            string word;\n            cin >> word;\n            analyzer.addReport(word);\n        } else if (cmd == \"HAS\") {\n            string word;\n            cin >> word;\n            cout << (analyzer.hasReport(word) ? \"YES\" : \"NO\") << \"\\n\";\n        } else if (cmd == \"LONGEST\") {\n            cout << analyzer.longestReport() << \"\\n\";\n        } else {\n            cout << analyzer.reportCount() << \"\\n\";\n        }\n    }\n    return 0;\n}\n',
  java: 'import java.util.*;\n\n__USER_CODE__\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int q = sc.nextInt();\n        ReportAnalyzer analyzer = new ReportAnalyzer();\n        StringBuilder out = new StringBuilder();\n        while (q-- > 0) {\n            String cmd = sc.next();\n            if (\"ADD\".equals(cmd)) {\n                analyzer.addReport(sc.next());\n            } else if (\"HAS\".equals(cmd)) {\n                out.append(analyzer.hasReport(sc.next()) ? \"YES\" : \"NO\").append(\'\\n\');\n            } else if (\"LONGEST\".equals(cmd)) {\n                out.append(analyzer.longestReport()).append(\'\\n\');\n            } else {\n                out.append(analyzer.reportCount()).append(\'\\n\');\n            }\n        }\n        System.out.print(out);\n    }\n}\n',
  python: '__USER_CODE__\n\nimport sys\n\n\ndef main() -> None:\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    q = int(data[0])\n    idx = 1\n    analyzer = ReportAnalyzer()\n    out = []\n    for _ in range(q):\n        cmd = data[idx]\n        idx += 1\n        if cmd == \"ADD\":\n            analyzer.add_report(data[idx])\n            idx += 1\n        elif cmd == \"HAS\":\n            out.append(\"YES\" if analyzer.has_report(data[idx]) else \"NO\")\n            idx += 1\n        elif cmd == \"LONGEST\":\n            out.append(str(analyzer.longest_report()))\n        else:\n            out.append(str(analyzer.report_count()))\n    sys.stdout.write(\"\\n\".join(out))\n    if out:\n        sys.stdout.write(\"\\n\")\n\n\nif __name__ == \"__main__\":\n    main()\n',
};

export const ROUND2_CODING_BANK: CodingSeed[] = [
  {
    title: 'Mission Ledger Sweep',
    description: 'Return the maximum sum of any contiguous segment in the dossier values.',
    inputFormat: ID_INPUT,
    outputFormat: 'Print the maximum contiguous subarray sum.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '8\n-2 1 -3 4 -1 2 1 -5\n',
    sampleOutput: '6\n',
    hiddenTestCases: [
      { input: '5\n1 2 3 4 5\n', expectedOutput: '15\n' },
      { input: '4\n-8 -3 -6 -2\n', expectedOutput: '-2\n' },
      { input: '6\n5 -2 7 -3 4 -1\n', expectedOutput: '11\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 1,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Cipher Window',
    description: 'Find the length of the longest substring without repeating characters in the incoming message.',
    inputFormat: 'A single lowercase string s.',
    outputFormat: 'Print the maximum length.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: 'abcaefbg\n',
    sampleOutput: '6\n',
    hiddenTestCases: [
      { input: 'bbbb\n', expectedOutput: '1\n' },
      { input: 'pwwkew\n', expectedOutput: '3\n' },
      { input: 'mission\n', expectedOutput: '4\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 2,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Rooftop Extraction Route',
    description: 'Compute the water trapped between rooftop heights after a storm.',
    inputFormat: ID_INPUT,
    outputFormat: 'Print the total trapped water.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '12\n0 1 0 2 1 0 1 3 2 1 2 1\n',
    sampleOutput: '6\n',
    hiddenTestCases: [
      { input: '6\n4 2 0 3 2 5\n', expectedOutput: '9\n' },
      { input: '5\n5 4 3 2 1\n', expectedOutput: '0\n' },
      { input: '5\n1 0 1 0 1\n', expectedOutput: '2\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 3,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Silent Stack Decoder',
    description: 'Verify whether the bracket sequence is balanced.',
    inputFormat: 'A single string containing only (), [] and {}.',
    outputFormat: 'Print VALID or INVALID.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: '{[()()]}\n',
    sampleOutput: 'VALID\n',
    hiddenTestCases: [
      { input: '([)]\n', expectedOutput: 'INVALID\n' },
      { input: '(((())))\n', expectedOutput: 'VALID\n' },
      { input: ']{\n', expectedOutput: 'INVALID\n' },
    ],
    difficulty: 'easy',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 4,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Asset BST Confirmation',
    description: 'Given a binary tree in level order with -1 for null, determine whether it is a valid BST.',
    inputFormat: 'The first line contains n. The second line contains n integers in level order where -1 means null.',
    outputFormat: 'Print YES if valid, otherwise NO.',
    constraints: '1 <= n <= 2 * 10^5',
    sampleInput: '7\n8 4 10 2 6 9 12\n',
    sampleOutput: 'YES\n',
    hiddenTestCases: [
      { input: '7\n5 1 4 -1 -1 3 6\n', expectedOutput: 'NO\n' },
      { input: '3\n2 1 3\n', expectedOutput: 'YES\n' },
      { input: '5\n10 5 15 -1 -1 6 20\n', expectedOutput: 'NO\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 5,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Intercept Merge',
    description: 'Merge two sorted intercepted streams into one sorted output.',
    inputFormat: 'The first line contains n and m. The second line has n sorted integers. The third line has m sorted integers.',
    outputFormat: 'Print the merged sorted sequence.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '4 3\n1 4 7 10\n2 5 8\n',
    sampleOutput: '1 2 4 5 7 8 10\n',
    hiddenTestCases: [
      { input: '1 4\n5\n1 2 3 4\n', expectedOutput: '1 2 3 4 5\n' },
      { input: '3 3\n1 1 1\n1 1 1\n', expectedOutput: '1 1 1 1 1 1\n' },
      { input: '2 0\n3 9\n\n', expectedOutput: '3 9\n' },
    ],
    difficulty: 'easy',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 6,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Codeword Rotation',
    description: 'Rotate the string left by k positions.',
    inputFormat: 'The first line contains s. The second line contains k.',
    outputFormat: 'Print the rotated string.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: 'cipher\n2\n',
    sampleOutput: 'pherci\n',
    hiddenTestCases: [
      { input: 'agent\n5\n', expectedOutput: 'agent\n' },
      { input: 'network\n9\n', expectedOutput: 'tworkne\n' },
      { input: 'aaaa\n1\n', expectedOutput: 'aaaa\n' },
    ],
    difficulty: 'easy',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 7,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Dead Drop Peaks',
    description: 'Count the local peaks in the terrain array. Endpoints count if they exceed their only neighbor.',
    inputFormat: ID_INPUT,
    outputFormat: 'Print the number of peaks.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '8\n1 3 2 5 4 6 1 0\n',
    sampleOutput: '3\n',
    hiddenTestCases: [
      { input: '1\n7\n', expectedOutput: '1\n' },
      { input: '5\n5 4 3 2 1\n', expectedOutput: '1\n' },
      { input: '6\n1 2 3 4 5 6\n', expectedOutput: '1\n' },
    ],
    difficulty: 'easy',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 8,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Signal Span',
    description: 'For each signal strength, print the stock span.',
    inputFormat: ID_INPUT,
    outputFormat: 'Print the span for each position.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '7\n100 80 60 70 60 75 85\n',
    sampleOutput: '1 1 1 2 1 4 6\n',
    hiddenTestCases: [
      { input: '5\n10 20 30 40 50\n', expectedOutput: '1 2 3 4 5\n' },
      { input: '5\n50 40 30 20 10\n', expectedOutput: '1 1 1 1 1\n' },
      { input: '6\n31 27 27 30 35 29\n', expectedOutput: '1 1 2 3 5 1\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 9,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Encrypted Phrase Collapse',
    description: 'Repeated adjacent duplicate letters cancel until none remain. Print EMPTY if the final string is empty.',
    inputFormat: 'A single lowercase string s.',
    outputFormat: 'Print the reduced string or EMPTY.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: 'abbaca\n',
    sampleOutput: 'ca\n',
    hiddenTestCases: [
      { input: 'azxxzy\n', expectedOutput: 'ay\n' },
      { input: 'aaaa\n', expectedOutput: 'EMPTY\n' },
      { input: 'network\n', expectedOutput: 'network\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 10,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Checkpoint Tree Signal',
    description: 'Compute the sum of all left leaf nodes in the tree.',
    inputFormat: 'The first line contains n. The second line contains n integers in level order where -1 means null.',
    outputFormat: 'Print the sum of left leaves.',
    constraints: '1 <= n <= 2 * 10^5',
    sampleInput: '7\n3 9 20 -1 -1 15 7\n',
    sampleOutput: '24\n',
    hiddenTestCases: [
      { input: '3\n1 2 3\n', expectedOutput: '2\n' },
      { input: '1\n5\n', expectedOutput: '0\n' },
      { input: '7\n10 5 12 3 -1 -1 14\n', expectedOutput: '3\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 11,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Agent Pair Sum',
    description: 'Count pairs of dossier values whose sum equals target k.',
    inputFormat: 'The first line contains n and k. The second line contains n integers.',
    outputFormat: 'Print the number of valid pairs.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '6 8\n1 7 2 6 3 5\n',
    sampleOutput: '3\n',
    hiddenTestCases: [
      { input: '5 4\n2 2 2 2 2\n', expectedOutput: '10\n' },
      { input: '4 100\n1 2 3 4\n', expectedOutput: '0\n' },
      { input: '7 6\n1 5 7 -1 5 1 2\n', expectedOutput: '3\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 12,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Agency Registry',
    description: 'Implement a registry abstraction. The fixed main performs ADD, UPDATE, GET, and TOP operations on agent scores.',
    inputFormat: 'The first line contains q operations.\nADD code score\nUPDATE code delta\nGET code\nTOP',
    outputFormat: 'Print results for GET and TOP. For TOP print EMPTY when no agents exist.',
    constraints: '1 <= q <= 2 * 10^5',
    sampleInput: '7\nADD ALPHA 30\nADD BRAVO 50\nGET ALPHA\nUPDATE ALPHA 25\nGET ALPHA\nTOP\nGET BRAVO\n',
    sampleOutput: '30\n55\n55\n50\n',
    hiddenTestCases: [
      { input: '5\nTOP\nADD X1 7\nTOP\nUPDATE X1 -2\nGET X1\n', expectedOutput: 'EMPTY\n7\n5\n' },
      { input: '6\nADD RED 10\nADD BLUE 12\nUPDATE RED 5\nTOP\nGET BLUE\nGET RED\n', expectedOutput: '15\n12\n15\n' },
      { input: '4\nADD FOX 1\nUPDATE FOX 9\nUPDATE FOX -3\nTOP\n', expectedOutput: '7\n' },
    ],
    difficulty: 'medium',
    points: 25,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 13,
    starterCode: REGISTRY_STARTER,
    wrappers: REGISTRY_WRAPPERS,
  },
  {
    title: 'Gadget Inventory',
    description: 'Implement an inventory abstraction. The fixed main issues STOCK, USE, COUNT, and TOTAL commands.',
    inputFormat: 'The first line contains q operations.\nSTOCK type count\nUSE type count\nCOUNT type\nTOTAL',
    outputFormat: 'Print results for COUNT and TOTAL.',
    constraints: '1 <= q <= 2 * 10^5',
    sampleInput: '7\nSTOCK DRONE 4\nSTOCK EMP 3\nCOUNT DRONE\nUSE DRONE 2\nCOUNT DRONE\nTOTAL\nCOUNT EMP\n',
    sampleOutput: '4\n2\n5\n3\n',
    hiddenTestCases: [
      { input: '4\nTOTAL\nSTOCK BUG 8\nUSE BUG 3\nCOUNT BUG\n', expectedOutput: '0\n5\n' },
      { input: '5\nSTOCK CAM 2\nSTOCK CAM 5\nUSE CAM 1\nCOUNT CAM\nTOTAL\n', expectedOutput: '6\n6\n' },
      { input: '6\nSTOCK A 1\nSTOCK B 2\nUSE B 2\nCOUNT B\nTOTAL\nCOUNT A\n', expectedOutput: '0\n1\n1\n' },
    ],
    difficulty: 'medium',
    points: 25,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 14,
    starterCode: INVENTORY_STARTER,
    wrappers: INVENTORY_WRAPPERS,
  },
  {
    title: 'Field Report Analyzer',
    description: 'Implement a report analyzer object. The fixed main uses ADD, HAS, LONGEST, and COUNT operations.',
    inputFormat: 'The first line contains q operations.\nADD word\nHAS word\nLONGEST\nCOUNT',
    outputFormat: 'Print results for HAS, LONGEST, and COUNT.',
    constraints: '1 <= q <= 2 * 10^5',
    sampleInput: '8\nCOUNT\nADD intel\nADD shadow\nHAS intel\nHAS echo\nLONGEST\nCOUNT\nHAS shadow\n',
    sampleOutput: '0\nYES\nNO\n6\n2\nYES\n',
    hiddenTestCases: [
      { input: '5\nADD a\nADD abcde\nLONGEST\nCOUNT\nHAS abcde\n', expectedOutput: '5\n2\nYES\n' },
      { input: '4\nHAS x\nLONGEST\nCOUNT\nADD zed\n', expectedOutput: 'NO\n0\n0\n' },
      { input: '6\nADD red\nADD carpet\nADD gala\nHAS gala\nLONGEST\nCOUNT\n', expectedOutput: 'YES\n6\n3\n' },
    ],
    difficulty: 'medium',
    points: 25,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 15,
    starterCode: ANALYZER_STARTER,
    wrappers: ANALYZER_WRAPPERS,
  },
];
